import type { Budget, Settings, Transaction } from '../services/storage'
export const currencies = [{code:'INR',symbol:'₹',name:'Indian Rupee',locale:'en-IN'},{code:'USD',symbol:'$',name:'US Dollar',locale:'en-US'},{code:'EUR',symbol:'€',name:'Euro',locale:'de-DE'},{code:'GBP',symbol:'£',name:'British Pound',locale:'en-GB'},{code:'AED',symbol:'د.إ',name:'UAE Dirham',locale:'en-AE'},{code:'CAD',symbol:'CA$',name:'Canadian Dollar',locale:'en-CA'},{code:'AUD',symbol:'A$',name:'Australian Dollar',locale:'en-AU'},{code:'SGD',symbol:'S$',name:'Singapore Dollar',locale:'en-SG'}] as const
export const formatMoney = (amount: number, currency = 'INR', compact = false) => { const c = currencies.find(x => x.code === currency) ?? currencies[0]; const safe = Number.isFinite(amount) ? amount : 0; return new Intl.NumberFormat(c.locale, { style: 'currency', currency: c.code, currencyDisplay: 'narrowSymbol', notation: compact ? 'compact' : 'standard', maximumFractionDigits: safe % 1 ? 2 : 0 }).format(safe) }
export const monthKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`
export const isInMonth = (date: string, key = monthKey()) => date.slice(0,7) === key
export const sum = (items: Transaction[], type: Transaction['type'], key = monthKey()) => items.filter(t=>t.type===type && isInMonth(t.date,key)).reduce((n,t)=>n+t.amount,0)
export function snapshot(transactions: Transaction[], settings: Settings, key = monthKey()) { const income = sum(transactions,'income',key), expenses = sum(transactions,'expense',key), dues = sum(transactions,'due',key); const budget = settings.monthlyBudget; return { income, expenses, dues, paidOut: expenses + dues, balance: settings.startingBalance + income - expenses - dues, budget, budgetUsed: budget ? expenses / budget * 100 : 0, budgetRemaining: Math.max(0,budget-expenses) } }
export const categorySpend = (transactions: Transaction[], category: string, key=monthKey()) => transactions.filter(t=>t.type==='expense'&&t.category===category&&isInMonth(t.date,key)).reduce((n,t)=>n+t.amount,0)
export const budgetState = (spent: number, limit: number) => limit <= 0 ? 'normal' : spent / limit >= 1 ? 'over' : spent / limit >= .85 ? 'near' : spent / limit >= .65 ? 'warning' : 'normal'
export const groupByDate = (items: Transaction[]) => items.reduce<Record<string,Transaction[]>>((all,t)=>{(all[t.date]??=[]).push(t);return all},{})
export const labelDate = (value:string) => { const today = new Date().toISOString().slice(0,10); const yesterday = new Date(Date.now()-86400000).toISOString().slice(0,10); if(value===today)return 'Today'; if(value===yesterday)return 'Yesterday'; return new Date(value+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}) }
export const newId = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`
export const seedBudgets = (categories:string[]):Budget[] => { const now=new Date().toISOString(); return categories.map((category,i)=>({id:newId(),category,limit:[7000,4000,8000,5000,3000][i]??3000,period:'monthly',createdAt:now,updatedAt:now})) }
